# Generated by Django 5.0.8 on 2024-08-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='slag',
            new_name='slug',
        ),
    ]
